title: "Spass mit Depressionen"
description: "Eine einfache Jekyll-basierte Homepage"
baseurl: "/SpassMitDepressionen"
url: "https://e1gen.github.io"
theme: minimal-mistakes
remote_theme: "mmistakes/minimal-mistakes@latest"
plugins:
  - jekyll-include-cache
